### ISSUE TITLE
PR Template 추가

### ISSUE THREAD

**Issue by kitaee** [Pilot-Server-Dev/pilot_instagram#4]
협업을 위한 PR Template 추가 부탁드립니다!

**Comment by SL313** [comment]
뱅크샐러드 코드리뷰 문화 도입

**Comment by SL313** [comment]
(H2 DB 테스트용 도입)

**Comment by SL313** [comment]
뒤늦게 참여하다 보니 할당된 업무를 확인하기가 어렵습니다. task 관리를 위한 툴이 하나 있으면 좋을 것 같습니다. 간단하게 노션도 괜찮습니다! 혹은 git issue를 잘 활용하는 방법도 좋을 것 같습니다! @kitaee

**Comment by kitaee** [comment]
좋습니다. 현재 자신이 하고 있는 업무를 git issue로 올리고 Assignees를 본인으로 걸면 알아보기 쉬울 것 같아요!
